### ISSUE TITLE
When creating a new pack, thumbnails will not be honored

### ISSUE THREAD

**Issue by noblereign** [Liusef/TelegramStickerManager#36]
If you create a new sticker pack, and set a thumbnail, the app will erroneously /skip the thumbnail setting portion.  
Not sure if it's not implemented, or just related to me using an icon larger than 100x100 and expecting the app to downsize it for me.  
 

Example in screenshot. The thumbnail I set shows up in the app, but in the end, it didn't even matter.  
 

![](https://user-images.githubusercontent.com/2935979/155834184-c1e50910-d702-4a7e-804b-f5d5aca5a8d1.png)

The icon that got set (first sticker in pack:)

![](https://user-images.githubusercontent.com/2935979/155834192-713327a7-3b2e-4f6c-8105-835d88d47509.png)

**Comment by Liusef** [comment]
Which version are you using, and could you send me the images in a private chat so I can test it?

I checked the code where it determines whether to skip or to upload a thumbnail and the only condition is whether the file exists. Is there a chance you may have moved the file between when you entered the pack details and started adding stickers?

[Here's the link to the code in question](https://github.com/Liusef/TelegramStickerManager/blob/174c1b98f7fbfe9b8b0761a8331219731ad5dd2a/ReunionApp/Runners/NewPackRunner.cs#L81)

**Comment by Liusef** [comment]
I think I've found the issue, I'll try and push a fix later today

**Comment by Liusef** [comment]
Thumbnails should work now, I can't push another release build for a while but it should be fixed for the next alpha release.
