### ISSUE TITLE
Add visual indicator that images are uploading

### ISSUE THREAD

**Issue by noblereign** [Liusef/TelegramStickerManager#74]
When adding stickers to a pack, it'd be nice if there was some sort of visual indicator that an image was uploading. Normally this is a non-issue for most circumstances, but for people on worse connections (e.g. using 4G LTE inside of a classroom [cough cough]) it can be a bit disconcerting when the app seems to get stuck.

Maybe display the sticker initially as black and white, and have it fill from bottom-up with color as the upload progresses? Perhaps maybe a Telegram-style progress bar? Heck, even a simple bar would do.
Terrible mockup for your viewing pleasures:
![image](https://user-images.githubusercontent.com/2935979/161150995-fcb80cf0-1e86-4d9e-9061-27647bf63546.png)

**Comment by Liusef** [comment]
I'm lazy so it doesn't look nearly that good

**Comment by noblereign** [comment]
That's fair
